import "./globals.css";
import { inter } from "@/components/fonts";

export const metadata = {
  title: "Clever Note",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased `}>
        <main >{children}</main>
      </body>
    </html>
  );
}
